[package]
name = "sign_passthrough"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ngx = { git = "https://github.com/nginxinc/ngx-rust", rev = "b08a9ee7a2bf9518acb1dac22fa3d241023047e5" }
libc = "0.2.159"
openssl = "0.10"
openssl-sys = "0.9"
hex = "0.4.3"
