services:
    nginx:
        build:
            context: ..
            dockerfile: Dockerfile.nginx
        ports:
            - '443:443'
        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
            - ./certs:/etc/nginx/certs
        depends_on:
            - flask

    flask:
        build:
            context: .
            dockerfile: Dockerfile.flask
        ports:
            - '5000:5000'
        volumes:
            - ./server:/app
