services:
    module-builder:
        build:
            context: ..
            dockerfile: Dockerfile.module
        volumes:
            - modules-volume:/sign-module

    nginx:
        image: nginx:1.27.2-alpine
        ports:
            - '443:443'
        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
            - modules-volume:/usr/lib/nginx/modules
            - ./certs:/etc/nginx/certs
        depends_on:
            - module-builder
    flask:
        build:
            context: .
            dockerfile: Dockerfile.flask
        ports:
            - '5000:5000'
        volumes:
            - ./server:/app

volumes:
    modules-volume:
